import = [
  "~/.config/alacritty/themes/themes/dark_plus.toml"
]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono"

[font.normal]
family = "JetBrainsMono"
style = "Regular"
